"""remove_unique_path

Revision ID: ab9dec71acf3
Revises: cedd960a171f
Create Date: 2023-11-09 20:03:14.165957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9dec71acf3'
down_revision: Union[str, None] = 'cedd960a171f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('minio_storage_path_key', 'minio_storage', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('minio_storage_path_key', 'minio_storage', ['path'])
    # ### end Alembic commands ###
