"""add_datetime

Revision ID: bb27bb64fa94
Revises: a66d4cf24df2
Create Date: 2023-11-11 21:33:48.793086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb27bb64fa94'
down_revision: Union[str, None] = 'a66d4cf24df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minio_storage', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('minio_storage', 'created')
    # ### end Alembic commands ###
